controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true

    position_controller:
      type: position_controllers/JointGroupPositionController
    arm_controller:
      type: position_controllers/JointTrajectoryController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

position_controller:
  ros__parameters:
    joints:
      - joint_swivel_front
      - joint_swivel_back
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

arm_controller:
  ros__parameters:
    action_monitor_rate: 20.0
    allow_integration_in_goal_trajectories: false
    allow_nonzero_velocity_at_trajectory_end: false
    allow_partial_joints_goal: false
    cmd_timeout: 0.0
    command_joints:
      - joint_arm_1
      - joint_arm_2
      - joint_arm_3
      - joint_arm_4
      - joint_arm_5
    joints:
      - joint_arm_1
      - joint_arm_2
      - joint_arm_3
      - joint_arm_4
      - joint_arm_5
    command_interfaces: 
      - position
    state_interfaces:
      - position
      - velocity
    constraints:
      goal_time: 0.0
    open_loop_control: false
    set_last_command_interface_value_as_state_on_activation: true
    position_feedback: true

velocity_controller:
  ros__parameters:
    joints:
      - joint_drivewheel_right
      - joint_drivewheel_left
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

