controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true

    position_controller:
      type: position_controllers/JointGroupPositionController
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

position_controller:
  ros__parameters:
    joints:
      - joint_swivel_front
      - joint_swivel_back
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

arm_controller:
  ros__parameters:
    action_monitor_rate: 20.0
    allow_integration_in_goal_trajectories: true
    allow_nonzero_velocity_at_trajectory_end: false
    allow_partial_joints_goal: true
    cmd_timeout: 0.0
    joints:
      - joint_arm_1
      - joint_arm_2
      - joint_arm_3
      - joint_arm_4
      - joint_arm_5
    command_interfaces: 
      - position
    state_interfaces:
      - position
      - velocity
    constraints:
      goal_time: 0.6

    position_feedback: true

velocity_controller:
  ros__parameters:
    joints:
      - joint_drivewheel_right
      - joint_drivewheel_left
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

gripper_controller:
  ros__parameters:
    action_monitor_rate: 20.0
    allow_integration_in_goal_trajectories: true
    allow_nonzero_velocity_at_trajectory_end: false
    allow_partial_joints_goal: true
    cmd_timeout: 0.0
    joints:
      - joint_gripper_base
      - joint_gripper_gear
      - joint_gripper_pad1
      - joint_gripper_pad2
    command_interfaces: 
      - position
    state_interfaces:
      - position
      - velocity
    constraints:
      goal_time: 0.6

    position_feedback: true
