controller_server:
  ros__parameters:
    use_sim_time: True
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: False
      min_vel_x: 0.0
      max_vel_x: 0.5
      max_vel_theta: 1.0
      acc_lim_x: 0.5
      acc_lim_theta: 1.0
      vx_samples: 10
      vtheta_samples: 20
      sim_time: 1.5          # seconds to roll-out trajectories
bt_navigator:
  ros__parameters:
    use_sim_time: True
    default_bt_xml_filename: "navigate_to_pose_w_replanning_time.xml"
